# Generated by Django 2.1.5 on 2019-02-10 11:12

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=users.models.imageFile),
        ),
    ]
