version: '3'

services:
  db:
    image: mysql
    volumes:
      # - "./sql:/var/lib/mysql"
      - "./sql/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: django
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: django
    ports:
      - "3306:3306"
  python:
    build: ./python
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db